### ISSUE TITLE
Rounding numbers ending with zeros error

### ISSUE THREAD

**Issue by SrdjanMilic** [SrdjanMilic/Super-Dynamic-Data#10]
Numbers should be displayed with two decimals: "1" as "1.00" or "1.4", should be "1.40".
Other numbers with no zero endings are displayed just fine.

![image](https://user-images.githubusercontent.com/28996115/115948710-09d46780-a4d0-11eb-8360-ba7dd940c83d.png)
---
![image](https://user-images.githubusercontent.com/28996115/115948723-2b355380-a4d0-11eb-8f7e-fd9e202dbc64.png)

**Comment by tanishghosh** [comment]
Hi @SrdjanMilic ! I have raised a PR to resolve this. Can you look into this?
https://github.com/SrdjanMilic/Super-Dynamic-Data/pull/13
